name: py38_gmct
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # - cudatoolkit=11.1.1  # Uncomment for CUDA.
  - ipython=8.1.1
  - matplotlib=3.4.3
  - networkx=2.6.3
  - numpy=1.21.2
  - pip=21.2.4
  - python=3.8.12
  - pytorch=1.9.1
  - r-base=3.6.1
  - r-essentials=3.6.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - six=1.16.0 
  - tqdm=4.62.3
  - pip:
    - lingam==1.5.5
    - rpy2==3.4.5
    - sdeint==0.2.4
    - torchdiffeq==0.2.2
